from pydantic import BaseModel, HttpUrl, Field
from typing import Optional

class BookBase(BaseModel):
    title: str
    author: str
    course_code: str
    description: str
    condition: str
    price: int
    location: str
    image_url: Optional[HttpUrl] = Field(default=None, description="This field is auto-generated by the server after image upload. Ignore on create.")

class BookCreate(BookBase):
    pass

class BookAPIModel(BookBase):
    id: int
    # seller_id: int      FOR LATER

    class Config:
        from_attributes = True